# Generated by Django 2.1 on 2022-09-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
